version: "2"
services:
  postgres:
    image: 'postgres:14.1-alpine'
    container_name: postgres
    ports:
     - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/
  eureka:
    image: 'eureka:latest'
    build:
      context: eureka
    container_name: eureka
    ports:
      - '8761:8761'
  gateway:
    build:
      context: gateway
    container_name: gateway
    ports:
      - '9898:9898'
  items:
    build:
      context: items
    container_name: items
    ports:
      - '9090:9090'
  users:
    build:
      context: users
    container_name: users
  app:
    build:
      context: frontend/app
    container_name: app
    ports:
      - '5000:5000'
  react-btn:
    build:
      context: frontend/react-btn
    container_name: react-btn
    ports:
      - '5001:5001'
  react-list:
    build:
      context: frontend/react-table
    container_name: react-list
    ports:
      - '5002:5002'
